<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>2 Computer exercises | Homework 1</title>
  <meta name="description" content="2 Computer exercises | Homework 1" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="2 Computer exercises | Homework 1" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="2 Computer exercises | Homework 1" />
  
  
  

<meta name="author" content="Chi-Yuan Fang" />


<meta name="date" content="2021-02-25" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="introduction.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">TA Session 1</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Textbook Exercises</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#exercise-2.6"><i class="fa fa-check"></i><b>1.1</b> Exercise 2.6</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#exercise-2.8"><i class="fa fa-check"></i><b>1.2</b> Exercise 2.8</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#exercise-2.14"><i class="fa fa-check"></i><b>1.3</b> Exercise 2.14</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#exercise-2.25"><i class="fa fa-check"></i><b>1.4</b> Exercise 2.25</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#exercise-3.2"><i class="fa fa-check"></i><b>1.5</b> Exercise 3.2</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#exercise-3.3"><i class="fa fa-check"></i><b>1.6</b> Exercise 3.3</a></li>
<li class="chapter" data-level="1.7" data-path="index.html"><a href="index.html#exercise-3.4"><i class="fa fa-check"></i><b>1.7</b> Exercise 3.4</a></li>
<li class="chapter" data-level="1.8" data-path="index.html"><a href="index.html#exercise-3.9"><i class="fa fa-check"></i><b>1.8</b> Exercise 3.9</a></li>
<li class="chapter" data-level="1.9" data-path="index.html"><a href="index.html#exercise-3.13"><i class="fa fa-check"></i><b>1.9</b> Exercise 3.13</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="computer-exercises.html"><a href="computer-exercises.html"><i class="fa fa-check"></i><b>2</b> Computer exercises</a><ul>
<li class="chapter" data-level="2.1" data-path="computer-exercises.html"><a href="computer-exercises.html#e3.2"><i class="fa fa-check"></i><b>2.1</b> E3.2</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>3</b> Introduction</a><ul>
<li class="chapter" data-level="3.1" data-path="introduction.html"><a href="introduction.html#ta-information"><i class="fa fa-check"></i><b>3.1</b> TA Information</a></li>
<li class="chapter" data-level="3.2" data-path="introduction.html"><a href="introduction.html#ta-sessions-schedule"><i class="fa fa-check"></i><b>3.2</b> TA Sessions Schedule</a></li>
<li class="chapter" data-level="3.3" data-path="introduction.html"><a href="introduction.html#reference"><i class="fa fa-check"></i><b>3.3</b> Reference</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-set-possum.html"><a href="data-set-possum.html"><i class="fa fa-check"></i><b>4</b> Data Set: <code>possum</code></a><ul>
<li class="chapter" data-level="4.1" data-path="data-set-possum.html"><a href="data-set-possum.html#data-description"><i class="fa fa-check"></i><b>4.1</b> Data Description</a><ul>
<li class="chapter" data-level="4.1.1" data-path="data-set-possum.html"><a href="data-set-possum.html#background"><i class="fa fa-check"></i><b>4.1.1</b> Background</a></li>
<li class="chapter" data-level="4.1.2" data-path="data-set-possum.html"><a href="data-set-possum.html#variables"><i class="fa fa-check"></i><b>4.1.2</b> Variables</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="data-set-possum.html"><a href="data-set-possum.html#input-data"><i class="fa fa-check"></i><b>4.2</b> Input Data</a><ul>
<li class="chapter" data-level="4.2.1" data-path="data-set-possum.html"><a href="data-set-possum.html#csv-file"><i class="fa fa-check"></i><b>4.2.1</b> <code>csv</code> File</a></li>
<li class="chapter" data-level="4.2.2" data-path="data-set-possum.html"><a href="data-set-possum.html#package"><i class="fa fa-check"></i><b>4.2.2</b> Package</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="data-set-possum.html"><a href="data-set-possum.html#data-cleaning"><i class="fa fa-check"></i><b>4.3</b> Data Cleaning</a><ul>
<li class="chapter" data-level="4.3.1" data-path="data-set-possum.html"><a href="data-set-possum.html#remove-missing-values"><i class="fa fa-check"></i><b>4.3.1</b> Remove Missing Values</a></li>
<li class="chapter" data-level="4.3.2" data-path="data-set-possum.html"><a href="data-set-possum.html#delete-rows-with-specific-conditions"><i class="fa fa-check"></i><b>4.3.2</b> Delete Rows with Specific Condition(s)</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="data-set-possum.html"><a href="data-set-possum.html#correlation"><i class="fa fa-check"></i><b>4.4</b> Correlation</a></li>
<li class="chapter" data-level="4.5" data-path="data-set-possum.html"><a href="data-set-possum.html#graphical-analysis"><i class="fa fa-check"></i><b>4.5</b> Graphical Analysis</a><ul>
<li class="chapter" data-level="4.5.1" data-path="data-set-possum.html"><a href="data-set-possum.html#scatter-plot"><i class="fa fa-check"></i><b>4.5.1</b> Scatter Plot</a></li>
<li class="chapter" data-level="4.5.2" data-path="data-set-possum.html"><a href="data-set-possum.html#box-plot-check-for-outliers"><i class="fa fa-check"></i><b>4.5.2</b> Box Plot: Check for Outliers</a></li>
<li class="chapter" data-level="4.5.3" data-path="data-set-possum.html"><a href="data-set-possum.html#density-plot-check-for-normality"><i class="fa fa-check"></i><b>4.5.3</b> Density Plot: Check for Normality</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="data-set-possum.html"><a href="data-set-possum.html#linear-regression"><i class="fa fa-check"></i><b>4.6</b> Linear Regression</a><ul>
<li class="chapter" data-level="4.6.1" data-path="data-set-possum.html"><a href="data-set-possum.html#model"><i class="fa fa-check"></i><b>4.6.1</b> Model</a></li>
<li class="chapter" data-level="4.6.2" data-path="data-set-possum.html"><a href="data-set-possum.html#residual-analysis"><i class="fa fa-check"></i><b>4.6.2</b> Residual Analysis</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Homework 1</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="computer-exercises" class="section level1">
<h1><span class="header-section-number">2</span> Computer exercises</h1>
<p>Do the following problem set from Stock &amp; Watson (4th Edition).</p>
<p>E3.2</p>
<div id="e3.2" class="section level2">
<h2><span class="header-section-number">2.1</span> E3.2</h2>
<blockquote>
<p>A consumer is given the chance to buy a baseball card for $1, but he declines
the trade. If the consumer is now given the baseball card, will he be willing to sell it for $1? Standard consumer theory suggests yes, but behavioral economists have found that “ownership” tends to increase the value of goods to
consumers. That is, the consumer may hold out for some amount more than
$1 (for example, $1.20) when selling the card, even though he was willing
to pay only some amount less than $1 (for example, $0.88) when buying it.
Behavioral economists call this phenomenon the “endowment effect.” John
List investigated the endowment effect in a randomized experiment involving
sports memorabilia traders at a sports-card show. Traders were randomly
given one of two sports collectibles, say good A or good B, that had approximately equal market value. Those receiving good A were then given the
option of trading good A for good B with the experimenter; those receiving
good B were given the option of trading good B for good A with the
experimenter. Data from the experiment and a detailed description can be
found on the text website, <a href="http://www.pearsonglobaleditions.com" class="uri">http://www.pearsonglobaleditions.com</a>, in the files <strong>Sportscards and Sportscards_Description</strong>.</p>
</blockquote>
<blockquote>
<ol style="list-style-type: lower-alpha">
<li><ol style="list-style-type: lower-roman">
<li>Suppose that, absent any endowment effect, all the subjects prefer good A to good B. What fraction of the experiment’s subjects would you expect to trade the good that they were given for the other good? (Hint:
Because of random assignment of the two treatments, approximately 50% of the subjects received good A, and 50% received good B.)</li>
<li>Suppose that, absent any endowment effect, 50% of the subjects prefer good A to good B, and the other 50% prefer good B to good A. What fraction of the subjects would you expect to trade the good they were given for the other good?</li>
<li>Suppose that, absent any endowment effect, <span class="math inline">\(X\%\)</span> of the subjects prefer good A to good B, and the other <span class="math inline">\((100 - X)\%\)</span> prefer good B to good A. Show that you would expect 50% of the subjects to trade the good they were given for the other good.</li>
</ol></li>
</ol>
</blockquote>
<p><strong>Solution</strong></p>
<ol style="list-style-type: lower-roman">
<li><p>A person will trade if he/she received good A but prefers good B or he/she received good B and prefers good A. 50% received good A, of these <span class="math inline">\(100\%\)</span> prefer good B; 50% receive good B, of these <span class="math inline">\(0\%\)</span> prefer good A. Thus, the expected fraction traded is
<span class="math display">\[\begin{align}
0.5 \times 1 + 0.5\times 0 = 0.5.
\end{align}\]</span></p></li>
<li><p>A person will trade if he/she received good A but prefers good B or he/she received good B and prefers good A. 50% received good A, of these <span class="math inline">\(50\%\)</span> prefer good B; 50% receive good B, of these <span class="math inline">\(50\%\)</span> prefer good A. Thus, the expected fraction traded is
<span class="math display">\[\begin{align}
0.5 \times 0.5 + 0.5\times 0.5 = 0.5.
\end{align}\]</span></p></li>
<li><p>A person will trade if he/she received good A but prefers good B or he/she received good B and prefers good A. 50% received good A, of these <span class="math inline">\((100-X)\%\)</span> prefer good B; 50% receive good B, of these <span class="math inline">\(X\%\)</span> prefer good A. Thus, the expected fraction traded is
<span class="math display">\[\begin{align}
0.5 \times (1-x) + 0.5x = 0.5
\end{align}\]</span>
where <span class="math inline">\(x = \frac{X}{100}\)</span>.</p></li>
</ol>
<blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li>Using the sports-card data, what fraction of the subjects traded the good they were given? Is the fraction significantly different from 50%? Is there evidence of an endowment effect? (Hint: Review Exercises 3.2 and 3.3.)</li>
</ol>
</blockquote>
<p><strong>Solution</strong></p>
<ul>
<li><strong>Prepare</strong></li>
</ul>
<p><span class="math inline">\(H_0: p= 0.5\)</span> (no endowment effect) v.s. <span class="math inline">\(H_A: p \neq 0.5\)</span> (endowment effect), where <span class="math inline">\(p\)</span> is the fraction of trades.</p>
<p>Let the significance level be <span class="math inline">\(0.05\)</span>.</p>
<ul>
<li><strong>Calculate</strong></li>
</ul>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="computer-exercises.html#cb1-1"></a><span class="co"># import data </span></span>
<span id="cb1-2"><a href="computer-exercises.html#cb1-2"></a><span class="kw">library</span>(readxl)</span>
<span id="cb1-3"><a href="computer-exercises.html#cb1-3"></a>sportscards &lt;-<span class="st"> </span><span class="kw">read_xlsx</span>(<span class="st">&quot;sportscards/Sportscards.xlsx&quot;</span>)</span>
<span id="cb1-4"><a href="computer-exercises.html#cb1-4"></a></span>
<span id="cb1-5"><a href="computer-exercises.html#cb1-5"></a><span class="co"># the fraction of trades</span></span>
<span id="cb1-6"><a href="computer-exercises.html#cb1-6"></a>fract_trade &lt;-<span class="st"> </span><span class="kw">mean</span>(sportscards<span class="op">$</span>trade)</span>
<span id="cb1-7"><a href="computer-exercises.html#cb1-7"></a>fract_trade</span></code></pre></div>
<pre><code>## [1] 0.3378378</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="computer-exercises.html#cb3-1"></a><span class="co"># standard error of the fraction of trades</span></span>
<span id="cb3-2"><a href="computer-exercises.html#cb3-2"></a>se_fract_trade &lt;-<span class="st"> </span><span class="kw">sd</span>(sportscards<span class="op">$</span>trade)<span class="op">/</span><span class="kw">sqrt</span>(<span class="kw">length</span>(sportscards<span class="op">$</span>trade))</span>
<span id="cb3-3"><a href="computer-exercises.html#cb3-3"></a>se_fract_trade</span></code></pre></div>
<pre><code>## [1] 0.03901015</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="computer-exercises.html#cb5-1"></a><span class="co"># test</span></span>
<span id="cb5-2"><a href="computer-exercises.html#cb5-2"></a><span class="kw">t.test</span>(sportscards<span class="op">$</span>trade, </span>
<span id="cb5-3"><a href="computer-exercises.html#cb5-3"></a>       <span class="dt">alternative =</span> <span class="kw">c</span>(<span class="st">&quot;two.sided&quot;</span>),</span>
<span id="cb5-4"><a href="computer-exercises.html#cb5-4"></a>       <span class="dt">mu =</span> <span class="fl">0.5</span>, <span class="co"># H0</span></span>
<span id="cb5-5"><a href="computer-exercises.html#cb5-5"></a>       <span class="dt">conf.level =</span> <span class="fl">0.95</span>) <span class="co"># alpha = 0.05</span></span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  sportscards$trade
## t = -4.1569, df = 147, p-value = 5.456e-05
## alternative hypothesis: true mean is not equal to 0.5
## 95 percent confidence interval:
##  0.2607447 0.4149310
## sample estimates:
## mean of x 
## 0.3378378</code></pre>
<ul>
<li><strong>Conclude</strong></li>
</ul>
<p>The fraction of trades in the sample was 0.3378, with a standard error of 0.0390.</p>
<p>Because <span class="math inline">\(p-value &lt; 0.05\)</span>, we reject <span class="math inline">\(H_0\)</span>. There is statistically significant evidence of an endowment effect.</p>
<blockquote>
<ol start="3" style="list-style-type: lower-alpha">
<li>Some have argued that the endowment effect may be present but that it is likely to disappear as traders gain more trading experience. Half of the experimental subjects were dealers, and the other half were nondealers. Dealers have more experience than nondealers. Repeat (b) for dealers and nondealers. Is there a significant difference in their behavior? Is the evidence consistent with the hypothesis that the endowment effect disappears as traders gain more experience? (Hint: Review Exercise 3.15.)</li>
</ol>
</blockquote>
<p><strong>Solution</strong></p>
<ol style="list-style-type: lower-roman">
<li>Dealers:</li>
</ol>
<ul>
<li><strong>Prepare</strong></li>
</ul>
<p><span class="math inline">\(H_0: p_1 = 0.5\)</span> (no endowment effect) v.s. <span class="math inline">\(H_A: p_1 \neq 0.5\)</span> (endowment effect), where <span class="math inline">\(p_1\)</span> is the fraction of trades for dealers.</p>
<p>Let the significance level be <span class="math inline">\(0.05\)</span>.</p>
<ul>
<li><strong>Calculate</strong></li>
</ul>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="computer-exercises.html#cb7-1"></a><span class="co"># dealer</span></span>
<span id="cb7-2"><a href="computer-exercises.html#cb7-2"></a>sportscards_dealer &lt;-<span class="st"> </span>sportscards[sportscards<span class="op">$</span>dealer <span class="op">==</span><span class="st"> </span><span class="dv">1</span>,]</span>
<span id="cb7-3"><a href="computer-exercises.html#cb7-3"></a></span>
<span id="cb7-4"><a href="computer-exercises.html#cb7-4"></a><span class="co"># the fraction of trades for dealers</span></span>
<span id="cb7-5"><a href="computer-exercises.html#cb7-5"></a>fract_trade_dealer &lt;-<span class="st"> </span><span class="kw">mean</span>(sportscards_dealer<span class="op">$</span>trade)</span>
<span id="cb7-6"><a href="computer-exercises.html#cb7-6"></a>fract_trade_dealer</span></code></pre></div>
<pre><code>## [1] 0.4459459</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="computer-exercises.html#cb9-1"></a><span class="co"># standard error of the fraction of trades for dealers</span></span>
<span id="cb9-2"><a href="computer-exercises.html#cb9-2"></a>se_fract_trade_dealer &lt;-<span class="st"> </span><span class="kw">sd</span>(sportscards_dealer<span class="op">$</span>trade)<span class="op">/</span><span class="kw">sqrt</span>(<span class="kw">length</span>(sportscards_dealer<span class="op">$</span>trade))</span>
<span id="cb9-3"><a href="computer-exercises.html#cb9-3"></a>se_fract_trade_dealer</span></code></pre></div>
<pre><code>## [1] 0.05817759</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="computer-exercises.html#cb11-1"></a><span class="co"># test</span></span>
<span id="cb11-2"><a href="computer-exercises.html#cb11-2"></a><span class="kw">t.test</span>(sportscards_dealer<span class="op">$</span>trade, </span>
<span id="cb11-3"><a href="computer-exercises.html#cb11-3"></a>       <span class="dt">alternative =</span> <span class="kw">c</span>(<span class="st">&quot;two.sided&quot;</span>),</span>
<span id="cb11-4"><a href="computer-exercises.html#cb11-4"></a>       <span class="dt">mu =</span> <span class="fl">0.5</span>, <span class="co"># H0</span></span>
<span id="cb11-5"><a href="computer-exercises.html#cb11-5"></a>       <span class="dt">conf.level =</span> <span class="fl">0.95</span>) <span class="co"># alpha = 0.05</span></span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  sportscards_dealer$trade
## t = -0.92912, df = 73, p-value = 0.3559
## alternative hypothesis: true mean is not equal to 0.5
## 95 percent confidence interval:
##  0.3299982 0.5618937
## sample estimates:
## mean of x 
## 0.4459459</code></pre>
<ul>
<li><strong>Conclude</strong></li>
</ul>
<p>The fraction of trades for dealers in the sample was 0.4459, with a standard error of 0.05818.</p>
<p>Because <span class="math inline">\(p-value &gt; 0.05\)</span>, we don’t reject <span class="math inline">\(H_0\)</span>. There is no evidence of an endowment effect.</p>
<ol start="2" style="list-style-type: lower-roman">
<li>Nondealers:</li>
</ol>
<ul>
<li><strong>Prepare</strong></li>
</ul>
<p><span class="math inline">\(H_0: p_2 = 0.5\)</span> (no endowment effect) v.s. <span class="math inline">\(H_A: p_2 \neq 0.5\)</span> (endowment effect), where <span class="math inline">\(p_2\)</span> is the fraction of trades for nondealers.</p>
<p>Let the significance level be <span class="math inline">\(0.05\)</span>.</p>
<ul>
<li><strong>Calculate</strong></li>
</ul>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="computer-exercises.html#cb13-1"></a><span class="co"># nondealer </span></span>
<span id="cb13-2"><a href="computer-exercises.html#cb13-2"></a>sportscards_nondealer &lt;-<span class="st"> </span>sportscards[sportscards<span class="op">$</span>dealer <span class="op">==</span><span class="st"> </span><span class="dv">0</span>,]</span>
<span id="cb13-3"><a href="computer-exercises.html#cb13-3"></a></span>
<span id="cb13-4"><a href="computer-exercises.html#cb13-4"></a><span class="co"># the fraction of trades for nondealers</span></span>
<span id="cb13-5"><a href="computer-exercises.html#cb13-5"></a>fract_trade_nondealer &lt;-<span class="st"> </span><span class="kw">mean</span>(sportscards_nondealer<span class="op">$</span>trade)</span>
<span id="cb13-6"><a href="computer-exercises.html#cb13-6"></a>fract_trade_nondealer</span></code></pre></div>
<pre><code>## [1] 0.2297297</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="computer-exercises.html#cb15-1"></a><span class="co"># standard error of the fraction of trades for nondealers</span></span>
<span id="cb15-2"><a href="computer-exercises.html#cb15-2"></a>se_fract_trade_nondealer &lt;-<span class="st"> </span><span class="kw">sd</span>(sportscards_nondealer<span class="op">$</span>trade)<span class="op">/</span><span class="kw">sqrt</span>(<span class="kw">length</span>(sportscards_nondealer<span class="op">$</span>trade))</span>
<span id="cb15-3"><a href="computer-exercises.html#cb15-3"></a>se_fract_trade_nondealer</span></code></pre></div>
<pre><code>## [1] 0.04923441</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="computer-exercises.html#cb17-1"></a><span class="co"># test</span></span>
<span id="cb17-2"><a href="computer-exercises.html#cb17-2"></a><span class="kw">t.test</span>(sportscards_nondealer<span class="op">$</span>trade, </span>
<span id="cb17-3"><a href="computer-exercises.html#cb17-3"></a>       <span class="dt">alternative =</span> <span class="kw">c</span>(<span class="st">&quot;two.sided&quot;</span>),</span>
<span id="cb17-4"><a href="computer-exercises.html#cb17-4"></a>       <span class="dt">mu =</span> <span class="fl">0.5</span>, <span class="co"># H0</span></span>
<span id="cb17-5"><a href="computer-exercises.html#cb17-5"></a>       <span class="dt">conf.level =</span> <span class="fl">0.95</span>) <span class="co"># alpha = 0.05</span></span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  sportscards_nondealer$trade
## t = -5.4895, df = 73, p-value = 5.559e-07
## alternative hypothesis: true mean is not equal to 0.5
## 95 percent confidence interval:
##  0.1316057 0.3278538
## sample estimates:
## mean of x 
## 0.2297297</code></pre>
<ul>
<li><strong>Conclude</strong></li>
</ul>
<p>The fraction of trades for nondealers in the sample was 0.2297, with a standard error of 0.0492.</p>
<p>Because <span class="math inline">\(p-value &lt; 0.05\)</span>, we reject <span class="math inline">\(H_0\)</span>. There is statistically significant evidence of an endowment effect.</p>
<ol start="3" style="list-style-type: lower-roman">
<li>Difference between dealers and nondealers:</li>
</ol>
<ul>
<li><strong>Prepare</strong></li>
</ul>
<p><span class="math inline">\(H_0: p_1 - p_2 = 0\)</span> v.s. <span class="math inline">\(H_A: p_1 - p_2 \neq 0\)</span>, where <span class="math inline">\(p_1\)</span> is the fraction of trades for dealers, and <span class="math inline">\(p_2\)</span> is the fraction of trades for nondealers.</p>
<p>Let the significance level be <span class="math inline">\(0.05\)</span>.</p>
<ul>
<li><strong>Calculate</strong></li>
</ul>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="computer-exercises.html#cb19-1"></a><span class="co"># difference</span></span>
<span id="cb19-2"><a href="computer-exercises.html#cb19-2"></a>trade_diff &lt;-<span class="st"> </span>sportscards_dealer<span class="op">$</span>trade <span class="op">-</span><span class="st"> </span>sportscards_nondealer<span class="op">$</span>trade</span>
<span id="cb19-3"><a href="computer-exercises.html#cb19-3"></a></span>
<span id="cb19-4"><a href="computer-exercises.html#cb19-4"></a><span class="co"># the fraction of trades for nondealers</span></span>
<span id="cb19-5"><a href="computer-exercises.html#cb19-5"></a>fract_trade_diff &lt;-<span class="st"> </span><span class="kw">mean</span>(trade_diff)</span>
<span id="cb19-6"><a href="computer-exercises.html#cb19-6"></a>fract_trade_diff</span></code></pre></div>
<pre><code>## [1] 0.2162162</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="computer-exercises.html#cb21-1"></a><span class="co"># standard error of the fraction of trades for nondealers</span></span>
<span id="cb21-2"><a href="computer-exercises.html#cb21-2"></a>se_fract_trade_diff &lt;-<span class="st"> </span><span class="kw">sd</span>(trade_diff)<span class="op">/</span><span class="kw">sqrt</span>(<span class="kw">length</span>(trade_diff))</span>
<span id="cb21-3"><a href="computer-exercises.html#cb21-3"></a>se_fract_trade_diff</span></code></pre></div>
<pre><code>## [1] 0.07268651</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="computer-exercises.html#cb23-1"></a><span class="kw">t.test</span>(trade_diff, </span>
<span id="cb23-2"><a href="computer-exercises.html#cb23-2"></a>       <span class="dt">alternative =</span> <span class="kw">c</span>(<span class="st">&quot;two.sided&quot;</span>),</span>
<span id="cb23-3"><a href="computer-exercises.html#cb23-3"></a>       <span class="dt">mu =</span> <span class="fl">0.5</span>, <span class="co"># H0</span></span>
<span id="cb23-4"><a href="computer-exercises.html#cb23-4"></a>       <span class="dt">conf.level =</span> <span class="fl">0.95</span>) <span class="co"># alpha = 0.05</span></span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  trade_diff
## t = -3.9042, df = 73, p-value = 0.0002088
## alternative hypothesis: true mean is not equal to 0.5
## 95 percent confidence interval:
##  0.07135221 0.36108022
## sample estimates:
## mean of x 
## 0.2162162</code></pre>
<ul>
<li><strong>Conclude</strong></li>
</ul>
<p>Because <span class="math inline">\(p-value &lt; 0.05\)</span>, we reject <span class="math inline">\(H_0\)</span>. There is statistically significant difference in the behavior of Traders and non-Traders.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="introduction.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
